### PR TITLE
Better AudioBlock

### PR DESCRIPTION
**Pull request by scart97**
* Expand AudioBlock to always include Resample and optionally DownmixMono and CropSignal, that way helping users with best choices
* Moved the file AudioBlock is present and changed some includes, this was necessary to fix a circular dependency problem that raised while importing the transforms into earlier notebooks.

### CODE REVIEW

**Comment by scart97** [comment]
Yes, it will be applied every item every epoch. Automatically detecting multiple sample rates is hard because I have no idea at which point we could do it, but caching could be a viable option.

**Comment by rbracco** [comment]
Reviewed the code and it looks pretty good but the new caching appears to have broken training in the tutorial nb (we dont have tests there). It appears `fn` is coming through as `None` sometimes.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-72550b717d1e> in <module>
----> 1 dbunch = auds.dataloaders(p10speakers, bs=64)

~/rob/fastai2/fastai2/data/block.py in dataloaders(self, source, path, verbose, **kwargs)
     96 
     97     def dataloaders(self, source, path='.', verbose=False, **kwargs):
---> 98         dsets = self.datasets(source)
     99         kwargs = {**self.dls_kwargs, **kwargs, 'verbose': verbose}
    100         return dsets.dataloaders(path=path, after_item=self.item_tfms, after_batch=self.batch_tfms, **kwargs)

~/rob/fastai2/fastai2/data/block.py in datasets(self, source, verbose)
     93         splits = (self.splitter or RandomSplitter())(items)
     94         pv(f"{len(splits)} datasets of sizes {','.join([str(len(s)) for s in splits])}", verbose)
---> 95         return Datasets(items, tfms=self._combine_type_tfms(), splits=splits, dl_type=self.dl_type, n_inp=self.n_inp, verbose=verbose)
     96 
     97     def dataloaders(self, source, path='.', verbose=False, **kwargs):

~/rob/fastai2/fastai2/data/core.py in __init__(self, items, tfms, tls, n_inp, dl_type, **kwargs)
    259     def __init__(self, items=None, tfms=None, tls=None, n_inp=None, dl_type=None, **kwargs):
    260         super().__init__(dl_type=dl_type)
--> 261         self.tls = L(tls if tls else [TfmdLists(items, t, **kwargs) for t in L(ifnone(tfms,[None]))])
    262         self.n_inp = (1 if len(self.tls)==1 else len(self.tls)-1) if n_inp is None else n_inp
    263 

~/rob/fastai2/fastai2/data/core.py in <listcomp>(.0)
    259     def __init__(self, items=None, tfms=None, tls=None, n_inp=None, dl_type=None, **kwargs):
    260         super().__init__(dl_type=dl_type)
--> 261         self.tls = L(tls if tls else [TfmdLists(items, t, **kwargs) for t in L(ifnone(tfms,[None]))])
    262         self.n_inp = (1 if len(self.tls)==1 else len(self.tls)-1) if n_inp is None else n_inp
    263 

~/rob/fastcore/fastcore/foundation.py in __call__(cls, x, *args, **kwargs)
     39             return x
     40 
---> 41         res = super().__call__(*((x,) + args), **kwargs)
     42         res._newchk = 0
     43         return res

~/rob/fastai2/fastai2/data/core.py in __init__(self, items, tfms, use_list, do_setup, split_idx, train_setup, splits, types, verbose)
    200         if do_setup:
    201             pv(f"Setting up {self.tfms}", verbose)
--> 202             self.setup(train_setup=train_setup)
    203 
    204     def _new(self, items, **kwargs): return super()._new(items, tfms=self.tfms, do_setup=False, types=self.types, **kwargs)

~/rob/fastai2/fastai2/data/core.py in setup(self, train_setup)
    219             for f in self.tfms.fs:
    220                 self.types.append(getattr(f, 'input_types', type(x)))
--> 221                 x = f(x)
    222             self.types.append(type(x))
    223         types = L(t if is_listy(t) else [t] for t in self.types).concat().unique()

~/rob/fastcore/fastcore/transform.py in __call__(self, x, **kwargs)
     69     @property
     70     def name(self): return getattr(self, '_name', _get_name(self))
---> 71     def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
     72     def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)
     73     def __repr__(self): return f'{self.name}: {self.use_as_item} {self.encodes} {self.decodes}'

~/rob/fastcore/fastcore/transform.py in _call(self, fn, x, split_idx, **kwargs)
     80         if split_idx!=self.split_idx and self.split_idx is not None: return x
     81         f = getattr(self, fn)
---> 82         if self.use_as_item or not is_listy(x): return self._do_call(f, x, **kwargs)
     83         res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
     84         return retain_type(res, x)

~/rob/fastcore/fastcore/transform.py in _do_call(self, f, x, **kwargs)
     85 
     86     def _do_call(self, f, x, **kwargs):
---> 87         return x if f is None else retain_type(f(x, **kwargs), x, f.returns_none(x))
     88 
     89 add_docs(Transform, decode="Delegate to `decodes` to undo transform", setup="Delegate to `setups` to set up transform")

~/rob/fastcore/fastcore/dispatch.py in __call__(self, *args, **kwargs)
     96         if not f: return args[0]
     97         if self.inst is not None: f = MethodType(f, self.inst)
---> 98         return f(*args, **kwargs)
     99 
    100     def __get__(self, inst, owner):

~/rob/fastai2_audio/nbs/fastai2_audio/core/signal.py in create(cls, fn, cache_folder, **kwargs)
     44     def create(cls, fn, cache_folder=None, **kwargs):
     45         if cache_folder is not None:
---> 46             fn = cache_folder / fn.name
     47         sig, sr = torchaudio.load(fn, **kwargs)
     48         return cls(sig, sr=sr)

AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by scart97** [comment]
Fixed, one partial function was incorrectly binding the cache_folder to the wrong argument, now 10 speakers is training and loading correctly from the cache

**Comment by scart97** [comment]
One item missing here: progress bar while preprocessing the audio

**Pull request merged**
